export const IPC = {
  CHAT_SEND: 'chat:send',
  CHAT_STOP: 'chat:stop',
  CHAT_CREATE: 'chat:create',
  CHAT_LIST: 'chat:list',
  CHAT_LOAD: 'chat:load',
  CHAT_DELETE: 'chat:delete',
  CHAT_RESUME_RETRY: 'chat:resume:retry',
  CHAT_RESUME_DISMISS: 'chat:resume:dismiss',
  BROWSER_NAVIGATE: 'browser:navigate',
  BROWSER_BACK: 'browser:back',
  BROWSER_FORWARD: 'browser:forward',
  BROWSER_REFRESH: 'browser:refresh',
  BROWSER_SET_BOUNDS: 'browser:set-bounds',
  BROWSER_TAB_NEW: 'browser:tab:new',
  BROWSER_TAB_LIST: 'browser:tab:list',
  BROWSER_TAB_SWITCH: 'browser:tab:switch',
  BROWSER_TAB_CLOSE: 'browser:tab:close',
  BROWSER_HISTORY_MATCH: 'browser:history-match',
  BROWSER_HIDE: 'browser:hide',
  BROWSER_SHOW: 'browser:show',
  SETTINGS_GET: 'settings:get',
  SETTINGS_SET: 'settings:set',
  TIER_GET: 'tier:get',
  TIER_SET: 'tier:set',
  WINDOW_MINIMIZE: 'window:minimize',
  WINDOW_MAXIMIZE: 'window:maximize',
  WINDOW_CLOSE: 'window:close',
} as const;

export const IPC_EVENTS = {
  CHAT_STREAM_TEXT: 'chat:stream:text',
  CHAT_STREAM_END: 'chat:stream:end',
  CHAT_RUN_START: 'chat:run:start',
  CHAT_RUN_END: 'chat:run:end',
  CHAT_TITLE_UPDATED: 'chat:title-updated',
  CHAT_TOOL_ACTIVITY: 'chat:tool-activity',
  CHAT_VERIFICATION: 'chat:verification',
  CHAT_RESUME_FAILED: 'chat:resume:failed',
  BROWSER_URL_CHANGED: 'browser:url-changed',
  BROWSER_TITLE_CHANGED: 'browser:title-changed',
  BROWSER_LOADING: 'browser:loading',
  BROWSER_TABS_CHANGED: 'browser:tabs-changed',
  BROWSER_AUTO_SHOW: 'browser:auto-show',
  BROWSER_MIRROR_NAVIGATE: 'browser:mirror-navigate',
  BROWSER_MIRROR_DONE: 'browser:mirror-done',
} as const;
